# Generated by Django 4.0.5 on 2022-06-14 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='Descripcion',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='Imagen',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='Titulo',
        ),
    ]
